"""add avatar_url to employees

Revision ID: 444b0316a32d
Revises: ff745c54fc73
Create Date: 2026-03-30 02:49:06.841601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '444b0316a32d'
down_revision: Union[str, Sequence[str], None] = 'ff745c54fc73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('avatar_url', sa.String(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('admin', 'hr', 'employee', name='userrole', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'employee'::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'hr', 'employee', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'employee'::character varying"))
    op.drop_column('employees', 'avatar_url')
    # ### end Alembic commands ###
